[tool.poetry]
name = "timermute"
version = "0.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
coverage = "^7.2.2"
isort = "^5.12.0"
mock = "^5.0.1"
pycodestyle = "^2.10.0"
pyppeteer = "^1.0.2"
pysimplegui = "^4.60.4"
python = "^3.11"
requests = "^2.28.2"
requests-html = "^0.10.0"
sqlalchemy = "^2.0.9"

[tool.isort]
multi_line_output = 9
line_length = 256

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
